### PR TITLE
Issue#32 -IBMi error fix

### PR DESCRIPTION
**Pull request by ashtkumar2023**
@robe070 , Kindly review the IBMi error fix.
[Issue32_IBMierror_VerifierReport.txt](https://github.com/lansa/db-regression/files/14023964/Issue32_IBMierror_VerifierReport.txt)

### CODE REVIEW

**Comment by robe070** [comment]
It looks like you've truncated the log file. I need to see this section too:
```
Windows -> iSeries: LANSA01_P50PGMLIB (SuperServer I/O).
```

**Comment by ashtkumar2023** [comment]
> It looks like you've truncated the log file. I need to see this section too:
> 
> ```
> Windows -> iSeries: LANSA01_P50PGMLIB (SuperServer I/O).
> ```

Report generation is going on still. Will upload it as soon as it is completed.

**Comment by ashtkumar2023** [comment]
[Verifier_Test_Summary.txt](https://github.com/lansa/db-regression/files/14045693/Verifier_Test_Summary.txt)

**Comment by robe070** [comment]
You've sent the summary file. I need Verifier_Test_Report.txt

**Comment by ashtkumar2023** [comment]
[Verifier_Test_Report.txt](https://github.com/lansa/db-regression/files/14046555/Verifier_Test_Report.txt)

**Pull request merged**
