### PR TITLE
Issue#36 - OAM Tests with Import Table Definitions

### PR DESCRIPTION
**Pull request by Netravati1205**
Added  All DB supported DD scripts and initial changes. 
New list has been created and adding to them, following standard protocol for object creation & naming conventions

### CODE REVIEW

**Review by robe070 — CHANGES_REQUESTED** [review]
There will need to be an sql script for each database. The 5 scripts need to be placed in the Scripts directory and committed to git. Name them like the existing sql scripts, starting with DB Type all in lower case. e.g. `mssql-table definition.sql`. Duplicate the sqlazure one. It will make resolving of the database easier at execution time.
That script needs to be imported into each LANSA System. 5 different tables. The resultant LANSA Tables need to be committed to git.

The code needs to test for DB Type and execute the specific test case for each DB Type.

**Comment by robe070** [comment]
It looks like you have rebased the wrong way around. The debug/paas commits do not match. See this screen grab. The commit ids are different. You have rewritten them.
image
There may be a better way than the following to fix it up, but this is my best idea:
You now need to create a new branch from the tip of debug/paas. Get the upstream latest before you do that. That assures you of no conflicts with it.
Then Cherry Pick just your changes from the current branch to your new branch.
A new PR is probably required.

**Comment by Netravati1205** [comment]
Okay I will create branch and get the upstream  and raise the PR,

**Comment by robe070** [comment]
Do you need some guidance with git?

**Comment by Netravati1205** [comment]
> Do you need some guidance with git?

That would faster , If you are available

**Pull request closed without merging**
