### PR TITLE
feature/Yashita

### PR DESCRIPTION
**Pull request by yashita-accolite**
Have added checks to see if the path exists for all logfiles (if it doesnt exist it writes a warning message to the host).
Have tested the script with all databasess and the write-host log for that is present in s3 at the following location for your reference:
s3://lansa-us-east-1/yashita/3.0/10a9d84c-fd1b-48ae-8926-ce6320eb5f4f/i-050c4fec3da2296dd/awsrunPowerShellScript/0.awsrunPowerShellScript/

### CODE REVIEW

**Review by robe070 — COMMENTED** [review]
On my system this file exists and possibly for other DB Types too:
`C:\Program Files (x86)\AZURESQL\Verifier_Test_Report.txt` does not exist. 

Are you sure it does not exist on your system?

**Comment by yashita-accolite** [comment]
> On my system this file exists and possibly for other DB Types too: `C:\Program Files (x86)\AZURESQL\Verifier_Test_Report.txt` does not exist.
> 
> Are you sure it does not exist on your system?

@robe070, it does exist for AZURESQL, the warning might be for MYSQL(I know its not completely setup yet but included it to have a test for all the dbs)

**Comment by robe070** [comment]
Check YOUR log file. ALL DB types say that file does not exist, except for LANSA (MSSQLS). So its a wrong message. Why is it wrong?

**Comment by yashita-accolite** [comment]
Sorry checked for Verifier_Test_Summary.txt earlier, C:\Program Files (x86)\AZURESQL\Verifier_Test_Report.txt does not exist in the vm (Verifier_Test_Report.txt doensnt exist for other databases as well ) I am using (instance ID: i-050c4fec3da2296dd)

**Pull request merged**
